name: boinc
base: core22
version: "7.23.0"
summary: BOINC lets you help cutting-edge science research using your computer.
description: |
  BOINC lets you help cutting-edge science research using your computer. The BOINC app, running on your computer, downloads scientific computing jobs and runs them invisibly in the background. It's easy and safe.
  About 30 science projects use BOINC. They investigate diseases, study climate change, discover pulsars, and do many other types of scientific research.
  The BOINC and Science United projects are located at the University of California, Berkeley and are supported by the National Science Foundation.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: amd64
    build-for: arm64
  - build-on: amd64
    build-for: armhf

apps:
  boinc:
    command: usr/bin/boinc --dir $HOME
    plugs:
    - network
    - network-bind

  client:
    command: usr/bin/boinc --dir $HOME
    plugs:
    - network
    - network-bind

  manager:
    command: usr/bin/boincmgr --datadir $HOME
    plugs:
    - network
    - network-bind
    extensions:
    - gnome
    slots:
    - dbus-manager
    common-id: boinc.manager
    environment:
      XAUTHORITY: $SNAP_REAL_HOME/.Xauthority

  screen:
    command: usr/bin/boincscr -boinc_dir $HOME
    plugs:
    - network
    - network-bind
    extensions:
    - gnome
    slots:
    - dbus-screen
    common-id: boinc.screen
    environment:
      XAUTHORITY: $SNAP_REAL_HOME/.Xauthority

slots:
  dbus-manager:
    interface: dbus
    bus: session
    name: boinc.manager
  dbus-screen:
    interface: dbus
    bus: session
    name: boinc.screen

parts:
  boinc:
    build-packages:
    - on amd64 to amd64:
      # gtk dependencies
      - libxcursor-dev:amd64
      - libxcomposite-dev:amd64
      - libxdamage-dev:amd64
      - libegl-dev:amd64
      # boinc dependencies
      - libnotify-dev:amd64
      - libxmu-dev:amd64
      - libxi-dev:amd64
      - libfcgi-dev:amd64
      - libxss-dev:amd64
      - libxcb-util-dev:amd64
      - libxxf86vm-dev:amd64
      - libxrender-dev:amd64
      - libxrandr-dev:amd64
      - libdbus-1-dev:amd64
      - libxtst-dev:amd64
    - on amd64 to arm64:
      # gtk dependencies
      - libxcursor-dev:arm64
      - libxcomposite-dev:arm64
      - libxdamage-dev:arm64
      - libegl-dev:arm64
      # boinc dependencies
      - libnotify-dev:arm64
      - libxmu-dev:arm64
      - libxi-dev:arm64
      - libfcgi-dev:arm64
      - libxss-dev:arm64
      - libxcb-util-dev:arm64
      - libxxf86vm-dev:arm64
      - libxrender-dev:arm64
      - libxrandr-dev:arm64
      - libdbus-1-dev:arm64
      - libxtst-dev:arm64
    - on amd64 to armhf:
      # gtk dependencies
      - libxcursor-dev:armhf
      - libxcomposite-dev:armhf
      - libxdamage-dev:armhf
      - libegl-dev:armhf
      # boinc dependencies
      - libnotify-dev:armhf
      - libxmu-dev:armhf
      - libxi-dev:armhf
      - libfcgi-dev:armhf
      - libxss-dev:armhf
      - libxcb-util-dev:armhf
      - libxxf86vm-dev:armhf
      - libxrender-dev:armhf
      - libxrandr-dev:armhf
      - libdbus-1-dev:armhf
      - libxtst-dev:armhf
    stage-packages:
    - on amd64 to amd64:
      - libxss-dev:amd64
    - on amd64 to arm64:
      - libxss-dev:arm64
    - on amd64 to armhf:
      - libxss-dev:armhf
    source: .
    plugin: autotools
    build-environment:
    - on amd64 to amd64:
      - triplet: x64-linux-snap
      - config_host: x86_64-pc-linux-gnu
      - boinc_platform: x86_64-pc-linux-gnu
      - alt_platform: ""
      - snap_pkg_config_path: ""
    - on amd64 to arm64:
      - triplet: arm64-linux-snap
      - config_host: aarch64-linux-gnu
      - boinc_platform: aarch64-unknown-linux-gnu
      - alt_platform: arm-unknown-linux-gnueabihf
      - snap_pkg_config_path: /usr/lib/aarch64-linux-gnu/pkgconfig/
    - on amd64 to armhf:
      - triplet: arm-linux-snap
      - config_host: arm-linux-gnueabihf
      - boinc_platform: arm-unknown-linux-gnueabihf
      - alt_platform: ""
      - snap_pkg_config_path: /usr/lib/arm-linux-gnueabihf/pkgconfig/
      - CXXFLAGS: -mfloat-abi=hard
    - VCPKG_DIR: "$PWD/3rdParty/linux/vcpkg/installed/$triplet"
    - PKG_CONFIG_PATH: "$VCPKG_DIR/lib/pkgconfig/:$snap_pkg_config_path"
    - _libcurl_pc: "$VCPKG_DIR/lib/pkgconfig/libcurl.pc"
    autotools-configure-parameters:
    - --prefix=/usr
    - --with-libcurl=$VCPKG_DIR
    - --with-ssl=$VCPKG_DIR
    - --with-wx-config=$VCPKG_DIR/tools/wxwidgets/wx-config
    - --host=$config_host
    - --with-boinc-platform=$boinc_platform
    - --with-boinc-alt-platform=$alt_platform
    - --enable-client
    - --enable-manager
    - --disable-server
    - GTK_LIBS="$(pkg-config --libs gtk+-3.0)"
    - CPPFLAGS="-DwxDEBUG_LEVEL=0"
    override-build: |
      echo ARCH=$SNAPCRAFT_TARGET_ARCH
      ./_autosetup
      craftctl default
