name: boinc
base: core22
version: "7.23.0"
summary: BOINC lets you help cutting-edge science research using your computer.
description: |
  BOINC lets you help cutting-edge science research using your computer. The BOINC app, running on your computer, downloads scientific computing jobs and runs them invisibly in the background. It's easy and safe.
  About 30 science projects use BOINC. They investigate diseases, study climate change, discover pulsars, and do many other types of scientific research.
  The BOINC and Science United projects are located at the University of California, Berkeley and are supported by the National Science Foundation.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: amd64
    build-for: arm64
  - build-on: amd64
    build-for: armhf

apps:
  boinc:
    command: usr/bin/boinc --dir $HOME
    plugs:
    - network
    - network-bind

  client:
    command: usr/bin/boinc --dir $HOME
    plugs:
    - network
    - network-bind

  manager:
    command: usr/bin/boincmgr --datadir $HOME
    plugs:
    - network
    - network-bind
    extensions:
    - gnome    
    slots:
    - dbus-daemon
    common-id: boinc.manager
    environment:
      XAUTHORITY: $SNAP_REAL_HOME/.Xauthority

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: boinc.manager

parts:
  boinc:
    build-packages:
    - on amd64 to arm64: 
      - libnotify-dev:arm64
      - libxmu-dev:arm64
      - libxi-dev:arm64
      - libfcgi-dev:arm64
      - libxss-dev:arm64
      - libxcb-util0-dev:arm64
      - libxxf86vm-dev:arm64
      - libxrender-dev:arm64
      - libxrandr-dev:arm64
      - libdbus-1-dev:arm64
      - libxtst-dev:arm64
    - on amd64 to armhf: 
      - libnotify-dev:armhf
      - libxmu-dev:armhf
      - libxi-dev:armhf
      - libfcgi-dev:armhf
      - libxss-dev:armhf
      - libxcb-util0-dev:armhf
      - libxxf86vm-dev:armhf
      - libxrender-dev:armhf
      - libxrandr-dev:armhf
      - libdbus-1-dev:armhf
      - libxtst-dev:armhf
    - else:
      - libnotify-dev
      - libxmu-dev
      - libxi-dev
      - libfcgi-dev
      - libxss-dev
      - libxcb-util0-dev
      - libxxf86vm-dev
      - libxrender-dev
      - libxrandr-dev
      - libdbus-1-dev
      - libxtst-dev
    stage-packages:
    - on amd64 to arm64:
      - libxss-dev:arm64
    - on amd64 to armhf:
      - libxss-dev:arm64
    - else:
      - libxss-dev
    source: .
    plugin: autotools
    build-environment:
    - triplet: $triplet
    - config_host: $config_host
    - boinc_platform: $boinc_platform
    - alt_platform: $alt_platform
    - VCPKG_DIR: "$PWD/3rdParty/linux/vcpkg/installed/$triplet"
    - _libcurl_pc: "$VCPKG_DIR/lib/pkgconfig/libcurl.pc"
    - PKG_CONFIG_PATH: "$VCPKG_DIR/lib/pkgconfig/:$snap_pkg_config_path"
    - on amd64 to armhf:
      - CXXFLAGS: -mfloat-abi=hard
    autotools-configure-parameters:
    - --prefix=$prefix
    - --with-libcurl=$VCPKG_DIR
    - --with-ssl=$VCPKG_DIR
    - --with-wx-config=$VCPKG_DIR/tools/wxwidgets/wx-config
    - --host=$config_host
    - --with-boinc-platform=$boinc_platform
    - --with-boinc-alt-platform=$alt_platform
    - --enable-client
    - --enable-manager
    - --disable-server
    - GTK_LIBS="`pkg-config --libs gtk+-3.0`"
    override-build: |
      echo ARCH=$SNAPCRAFT_TARGET_ARCH
      ./_autosetup
      snapcraftctl build
