name: Dart ubuntu
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '5 12 * * 0'


jobs:
  build:
    name: ${{ matrix.type }}-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [linux android]

      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          
      - name: Set up JDK 1.9
        uses: actions/setup-java@v1
        with:
          java-version: 1.9

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Dart SDK
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: beta

      - name: Cache dependencies
        uses: actions/cache@v2.1.3
        with:
          path: 3rdParty/buildCache
          key: dart-${{ matrix.type }}-${{ hashFiles('android/*.sh', 'dart/*.sh') }}          
      
      - name: Install dependencies
        run: dart pub get
        
      - name: Setting Linux Desktop
        if: matrix.type == 'linux'
        run: flutter config --enable-linux-desktop
        
      - name: Build Linux
        if: matrix.type == 'linux'
        run: cd dart/boinc/ && flutter build linux
        
      - name: Build Android
        if: matrix.type == 'android'
        run: cd dart/boinc/ && flutter build apk
