name: Docker
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron:  '10 12 * * 0'

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
  AWS_DEFAULT_REGION: us-west-2

jobs:
  docker_build:
    name: snap-build-arm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
        # - linux/amd64
        # - linux/arm64
        - linux/arm/v7
    container:
      image: diddledan/snapcraft:core20
      volumes:
      - /sys
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      options: --security-opt apparmor:unconfined --privileged --platform ${{ matrix.architecture }}
    steps:
    - name: tal
      if: success()
      run: |
        echo tal
