name: Snap
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron:  '10 12 * * 0'

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
  AWS_DEFAULT_REGION: us-west-2

jobs:
  docker_build:
    name: snap-${{ matrix.type }}-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - type: arm
          architecture: armhf
        - type: arm64
          architecture: arm64
        - type: x64
          architecture: amd64
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y p7zip-full

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          3rdParty/buildCache
          !3rdParty/buildCache/linux/vcpkgcache/
        key: snap-${{ matrix.type }}-${{ hashFiles('3rdParty/vcpkg_ports/aws_version.txt', '3rdParty/vcpkg_ports/ninja_version.txt') }}

    - name: Running from origin repo
      if: ${{ success() && env.AWS_ACCESS_KEY_ID != 0 && env.AWS_SECRET_ACCESS_KEY != 0 }}
      run: |
        echo "VCPKG_BINARY_SOURCES=clear;x-aws,s3://vcpkg.cache.boinc/,readwrite" >> $GITHUB_ENV

    - name: Running from fork
      if: ${{ success() && (env.AWS_ACCESS_KEY_ID == 0 || env.AWS_SECRET_ACCESS_KEY == 0) }}
      run: |
        echo "VCPKG_BINARY_SOURCES=clear;x-aws-config,no-sign-request;x-aws,s3://vcpkg.cache.boinc/,read" >> $GITHUB_ENV
      
    - name: Configure docker qemu
      if: success()
      uses: docker/setup-qemu-action@v2

    - name: Build boinc snap
      if: success()
      id: snapcraft
      uses: diddlesnaps/snapcraft-multiarch-action@v1
      with:
        architecture: ${{ matrix.architecture }}
        snapcraft-args: snap --destructive-mode

    - name: cache aws-cli and ninja
      if: success()
      run: |
        if [ ! -d "3rdParty/buildCache/linux/awscli/" ]; then
          echo "Caching aws-cli"
          mkdir -p 3rdParty/buildCache/linux/awscli/
          sudo chown -R $USER parts/boinc/build/3rdParty/buildCache/linux/awscli/
          cp -R parts/boinc/build/3rdParty/buildCache/linux/awscli/ 3rdParty/buildCache/linux/
        fi
        if [ ! -d "3rdParty/buildCache/linux/ninja/" ]; then
          echo "Caching ninja"
          mkdir -p 3rdParty/buildCache/linux/ninja/
          sudo chown -R $USER parts/boinc/build/3rdParty/buildCache/linux/ninja/
          cp -R parts/boinc/build/3rdParty/buildCache/linux/ninja/ 3rdParty/buildCache/linux/
        fi

    - name: Install boinc snap x64
      if: success() && matrix.type == 'x64'
      run: sudo snap install --devmode ${{ steps.snapcraft.outputs.snap }}

    - name: Test boinc client snap x64
      if: success() && matrix.type == 'x64'
      run: | 
        boinc --version
        boinc.client --version

    - name: Prepare logs on failure
      if: ${{ failure() }}
      run: python ./deploy/prepare_deployment.py logs

    - name: Upload logs on failure
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: snap_logs_${{ github.event.pull_request.head.sha }}
        path: deploy/logs.7z

    - name: Prepare artifacts for deploy
      if: success() 
      run: python ./deploy/prepare_deployment.py linux_snap

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: linux_snap_${{ matrix.type }}_${{ github.event.pull_request.head.sha }}
        path: deploy/linux_snap.7z
