name: 'Test Report'
on:
  workflow_run:
    workflows: ['Android']                # runs after Android workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: android_junit_result    # artifact name
        name: Junit Android Tests         # Name of the check run which will be created
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: java-junit  